# Generated by Django 6.0 on 2025-12-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itanery_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['flight_type'], 'verbose_name': 'Flight', 'verbose_name_plural': 'Flights'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Hotel', 'verbose_name_plural': 'Hotels'},
        ),
        migrations.AlterModelOptions(
            name='itinerary',
            options={'ordering': ['customer', 'day'], 'verbose_name': 'Itinerary Day', 'verbose_name_plural': 'Itinerary Days'},
        ),
        migrations.AlterModelOptions(
            name='itinerarydetail',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Activity Detail', 'verbose_name_plural': 'Activity Details'},
        ),
        migrations.AlterModelOptions(
            name='packageexclusion',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Package Exclusion', 'verbose_name_plural': 'Package Exclusions'},
        ),
        migrations.AlterModelOptions(
            name='packageinclusion',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Package Inclusion', 'verbose_name_plural': 'Package Inclusions'},
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.AddField(
            model_name='itinerarydetail',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.AddField(
            model_name='packageexclusion',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.AddField(
            model_name='packageinclusion',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.CharField(max_length=100, verbose_name='Airline'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='cabin',
            field=models.CharField(choices=[('Economy', 'Economy'), ('Premium Economy', 'Premium Economy'), ('Business', 'Business'), ('First Class', 'First Class')], default='Economy', max_length=20, verbose_name='Cabin Class'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_type',
            field=models.CharField(choices=[('departure', 'Departure'), ('flight2', 'Connecting Flight'), ('return', 'Return')], max_length=20, verbose_name='Flight Type'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.URLField(help_text='External image URL', verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Hotel Name'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='nights',
            field=models.CharField(help_text='e.g., 3 Nights', max_length=50, verbose_name='Number of Nights'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='room_type',
            field=models.CharField(help_text='e.g., Deluxe Suite', max_length=100, verbose_name='Room Type'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='stars',
            field=models.IntegerField(choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')], verbose_name='Star Rating'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='icon',
            field=models.CharField(default='📍', help_text='Emoji icon (e.g., 🏛️, 🕌, 🛍️)', max_length=10),
        ),
        migrations.AlterField(
            model_name='video',
            name='local_src',
            field=models.CharField(help_text='Path: /static/videos/tour.mp4 or external URL', max_length=500, verbose_name='Video Source Path'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default='Experience a Glimpse of Your Journey', max_length=200, verbose_name='Video Title'),
        ),
        migrations.AlterField(
            model_name='whatsappconfig',
            name='message',
            field=models.TextField(default='I want to finalize this itinerary!', verbose_name='Default Message'),
        ),
        migrations.AlterField(
            model_name='whatsappconfig',
            name='phone',
            field=models.CharField(help_text='Format: 919876543210 (country code + number, no spaces)', max_length=20, verbose_name='WhatsApp Phone Number'),
        ),
        migrations.AlterUniqueTogether(
            name='itinerary',
            unique_together={('customer', 'day')},
        ),
    ]
