# Generated by Django 6.0 on 2025-12-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itanery_app', '0003_alter_flight_options_alter_hotel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='local_src',
            field=models.CharField(blank=True, help_text='YouTube video ID (e.g., dQw4w9WgXcQ) or full YouTube URL', max_length=500, null=True, verbose_name='YouTube Video ID/URL'),
        ),
    ]
