# Generated by Django 6.0 on 2025-12-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itanery_app', '0004_alter_video_local_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='local_src',
            field=models.CharField(help_text='Path: /static/videos/tour.mp4 or external URL', max_length=500, verbose_name='Video Source Path'),
        ),
    ]
