# Generated by Django 6.0 on 2025-12-23 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Customer Name')),
                ('destination', models.CharField(max_length=200, verbose_name='Destination')),
                ('dates', models.CharField(max_length=100, verbose_name='Travel Dates')),
                ('guests', models.CharField(max_length=100, verbose_name='Number of Guests')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_type', models.CharField(choices=[('departure', 'Departure'), ('flight2', 'Connecting Flight'), ('return', 'Return')], max_length=20)),
                ('from_location', models.CharField(max_length=100, verbose_name='From (City/Airport)')),
                ('to_location', models.CharField(max_length=100, verbose_name='To (City/Airport)')),
                ('date', models.CharField(max_length=100, verbose_name='Flight Date')),
                ('time', models.CharField(max_length=50, verbose_name='Flight Time')),
                ('airline', models.CharField(max_length=100)),
                ('flight_number', models.CharField(max_length=50, verbose_name='Flight Number')),
                ('cabin', models.CharField(choices=[('Economy', 'Economy'), ('Premium Economy', 'Premium Economy'), ('Business', 'Business'), ('First Class', 'First Class')], default='Economy', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='itanery_app.customer')),
            ],
            options={
                'verbose_name': 'Flight',
                'verbose_name_plural': 'Flights',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.URLField(verbose_name='Image URL')),
                ('nights', models.CharField(help_text='e.g., 3 Nights', max_length=50)),
                ('room_type', models.CharField(max_length=100, verbose_name='Room Type')),
                ('stars', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')])),
                ('map_url', models.URLField(verbose_name='Google Maps URL')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='itanery_app.customer')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(verbose_name='Day Number')),
                ('icon', models.CharField(default='📍', help_text='Emoji icon', max_length=10)),
                ('title', models.CharField(max_length=200, verbose_name='Day Title')),
                ('description', models.TextField(verbose_name='Day Description')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='itanery_app.customer')),
            ],
            options={
                'verbose_name': 'Itinerary Day',
                'verbose_name_plural': 'Itinerary Days',
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50, verbose_name='Time')),
                ('activity', models.TextField(verbose_name='Activity Description')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='itanery_app.itinerary')),
            ],
            options={
                'verbose_name': 'Activity Detail',
                'verbose_name_plural': 'Activity Details',
            },
        ),
        migrations.CreateModel(
            name='PackageExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=300, verbose_name='Excluded Item')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='itanery_app.customer')),
            ],
            options={
                'verbose_name': 'Package Exclusion',
                'verbose_name_plural': 'Package Exclusions',
            },
        ),
        migrations.CreateModel(
            name='PackageInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=300, verbose_name='Included Item')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='itanery_app.customer')),
            ],
            options={
                'verbose_name': 'Package Inclusion',
                'verbose_name_plural': 'Package Inclusions',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Experience a Glimpse of Your Journey', max_length=200)),
                ('local_src', models.CharField(help_text='Path: /static/videos/tour.mp4', max_length=500)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='itanery_app.customer')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Format: 919876543210 (with country code)', max_length=20)),
                ('message', models.TextField(default='I want to finalize this itinerary!')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp', to='itanery_app.customer')),
            ],
            options={
                'verbose_name': 'WhatsApp Configuration',
                'verbose_name_plural': 'WhatsApp Configurations',
            },
        ),
    ]
