# Generated by Django 6.0 on 2025-12-25 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itanery_app', '0002_alter_flight_options_alter_hotel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['date', 'time'], 'verbose_name': 'Flight', 'verbose_name_plural': 'Flights'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['order'], 'verbose_name': 'Hotel', 'verbose_name_plural': 'Hotels'},
        ),
        migrations.AlterModelOptions(
            name='itinerary',
            options={'ordering': ['day'], 'verbose_name': 'Itinerary Day', 'verbose_name_plural': 'Itinerary Days'},
        ),
        migrations.AlterModelOptions(
            name='itinerarydetail',
            options={'ordering': ['order'], 'verbose_name': 'Activity Detail', 'verbose_name_plural': 'Activity Details'},
        ),
        migrations.AlterModelOptions(
            name='packageexclusion',
            options={'ordering': ['order'], 'verbose_name': 'Package Exclusion', 'verbose_name_plural': 'Package Exclusions'},
        ),
        migrations.AlterModelOptions(
            name='packageinclusion',
            options={'ordering': ['order'], 'verbose_name': 'Package Inclusion', 'verbose_name_plural': 'Package Inclusions'},
        ),
    ]
